version: "3.9"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thesis_db
      MYSQL_USER: thesis
      MYSQL_PASSWORD: thesis
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--default-authentication-plugin=mysql_native_password"
    ]
    ports: ["3306:3306"]
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: {}